### ISSUE TITLE
Fighter_FaithfulMount not returning equipment

### ISSUE THREAD

**Issue by toasted323** [toasted323/CoffeeMud#16]

**Comment by toasted323** [comment]
@ParreaBob need more information here, also see #13

**Comment by toasted323** [comment]
@ParreaBob What was going wrong here? Could you please add details of the buggy behaviour, how to reproduce it and what was expected?

**Comment by ParreaBob** [comment]
The command suggests that a cavaliers mount will grab his body and take it back to the recall location.

What actually happens is the mount and the body (and all equipment lol) disappear and never return lol

**Comment by ParreaBob** [comment]
I would have to add it to a cavalier. I removed the ability from the class

**Comment by toasted323** [comment]
Thanks I'll test it locally. Technically it disappeared into a hidden room. This is somewhat different from the quickchange skill issue. Here the implementation 
- moves the corpse into the mounts inventory
- puts the mount into a hidden room and then
- tries to reach the player every 1-60 second for like 500 times

So its more or less by design to not be accessible after a while (e.g. if you die and immediately log out for a day.)

Need to test, to understand if there is a real bug, or if its just a broken user experience.

**Comment by toasted323** [comment]
> 20241222.1138.02 debug Fighter_Faithf Death event triggered for Flar
20241222.1138.02 debug Fighter_Faithf No suitable mount found for Flar

**Comment by toasted323** [comment]
> 20241222.1138.02 debug Fighter_Faithf Death event triggered for Alice
20241222.1138.02 debug Fighter_Faithf No suitable mount found for Alice

This first logging feedback suggests that this might be an expectation gap, several conditions have to be satisified to have a mount pick up the corpse in the first place:

- Group Membership: The dead character must be in a group with potential mounts
- Mount Characteristics:
   - NPC
   - Animal intelligence
   - Rideable
   - Same location 
   - It must be alive, awake, mobile, and unbound
   - Must be among the characters set of favored mounts

@ParreaBob Does that match your idea of how the skill  is supposed to work?

**Comment by ParreaBob** [comment]
Yes it does

**Comment by toasted323** [comment]
> 20241222.1215.47 debug Fighter_Faithf Trailer runnable started for Alice
20241222.1215.47 debug Fighter_Faithf Conditions met for corpse retrieval
20241222.1215.47 debug Prop_ArenaSpec executeMsg called with message: 
20241222.1215.47 debug Fighter_Faithf Corpse found: the body of Alice
20241222.1215.47 debug Fighter_Faithf Trailer runnable started for Alice
20241222.1215.47 debug Fighter_Faithf Conditions met for corpse retrieval
20241222.1215.47 debug Fighter_Faithf Corpse not found for Alice
20241222.1215.47 debug Fighter_Faithf Corpse moved to mount: a horse

> possess horse
i
You are carrying:
      The body of Alice 

Additionally
- There was no visible dead corpse, for observers the character died and no corpse is visible.

**Comment by toasted323** [comment]
Additional mechanics:
- if the horse was in combat when the character died, combat is forcibly ended ("makePeace") before the body is moved.
- the horse will move out of the room, but only if no other potential "rider" is present.
- if a rider is present and in the same room, the horse will stop there and do nothing with the body in inventory.

**Comment by toasted323** [comment]
The implementation suggests that at least two final states exist that remove the corpse from the players reach completely.
Based on this understanding the skill is considered unusable, deprecated and considered for future removal.
