### ISSUE TITLE
[EPIC] hide level and class information

### ISSUE THREAD

**Issue by toasted323** [toasted323/CoffeeMud#34]
In general class and level are shown when 
 - they are not disabled
 - they are not configured as private and the context is not "self examination"
 - the viewed MOB is not level or classless
 - the viewing MOB is an archon (SYSOP)

This leads to complex conditional logic, details in the respective user stories

Related stories:

- #6 
- #28 
- #32 
- #62 
- #33

**Comment by ParreaBob** [comment]
Also from the group command. Personally, I would like to hunt down every instance of a player seeing the level of another player. Obv archons can snoop order player score and thats good
