### ISSUE TITLE
Hide level and class from who command

### ISSUE THREAD

**Issue by toasted323** [toasted323/CoffeeMud#6]
- archons/sysops see class and level, even if its private, but not if its disabled

See also: whois, clanwho

See also: #28

**Comment by toasted323** [comment]
@ParreaBob I think the web app shows level and class information too, should we consider that for removal too?

**Comment by ParreaBob** [comment]
Yes please, and look

**Comment by toasted323** [comment]
yea  a heads up though, its likely going to be step by step removal: first who, then look then web then a configuration option to hide show these details.

**Comment by ParreaBob** [comment]
Perfect! What are your thoughts on a who off command? I am personally against it but if you and the others want that it is something else to explore

**Comment by toasted323** [comment]
same for me, I'd prefer to have that level of transparency

**Comment by ParreaBob** [comment]
Then its decided. I'm of the opinion if there are players (eg Ruby) who make people hide like that we deal with the problem and not take a passive aggressive approach. A very public and transparent approach to disciplining behavior.
